paths:
  documents: testdata/documents
  partials: testdata/partials
  output: testdata/output

mjml:
  validationLevel: "soft"
  keepComments: true
  beautify: false
  minify: false

template:
  preserveHrefExpressions: true

  variables:
    companyName: ACME Corp
    supportEmail: support@acme.com
    year: 2024

  documents:
    welcome:
      title: Welcome Email
      variables:
        companyName: Other Corp
        activationLink: https://example.com/activate
    invoice:
      title: Invoice Template
      variables:
        invoiceNumber: INV-001
        items:
          - name: Blue Jeans
            quantity: 1
            price: "99,99"
          - name: White Shirt
            quantity: 2
            price: "59,98"