name: Release
on:
  push:
  pull_request:
    branches: [main]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: Build Release
        run: make release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/darwin-amd64/mjml-dev
            bin/darwin-arm64/mjml-dev
            bin/linux-amd64/mjml-dev
            bin/linux-arm64/mjml-dev
            bin/windows-amd64/mjml-dev.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}